# general settings
name: train_DTMS1
model_type: DTMS1Model
scale: 1
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 8 GPUs
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: DeblurPairedDataset

    dataroot_gt: /home/b109/lxb/DTM-master/DTM-demo/dataset/train/full
    dataroot_lq: /home/b109/lxb/DTM-master/DTM-demo/dataset/train/low

    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk


    num_worker_per_gpu: 1
    batch_size_per_gpu: 2
    mini_batch_sizes: [4]#[8,4,2,2,1,1]             # Batch size per gpu   
    #iters: [92000,80000,38000,33000,33000,24000]
    iters: [300000]
    gt_size: 256   # Max patch size for progressive training
    gt_sizes: [256]#[192, 256,320,384,464,512]  # Patch sizes for progressive training.

    # data loader
    use_shuffle: true
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val:
    name: ValSet
    type: DeblurPairedDataset

    dataroot_gt: /home/b109/lxb/DTM-master/DTM-demo/dataset/val/full
    dataroot_lq: /home/b109/lxb/DTM-master/DTM-demo/dataset/val/low

    io_backend:
      type: disk

# network structures
network_g:
  type: DTMS1
  n_encoder_res: 5
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [3,5,6,6]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2
  bias: False
  LayerNorm_type: WithBias

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~ 

# training settings
train:
  ema_decay: 0.999

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000]       
    restart_weights: [1,1]
    eta_mins: [0.000285,0.000001]  

  total_iter: 300000
  warmup_iter: -1  # no warm up

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# Uncomment these for validation
# validation settings
val:
  val_freq: !!float 5e3
  save_img: False

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
